workspace = s[true], gapsout:50
animation = specialWorkspace, 1, 8, default, slidefadevert 5%

# konsole
workspace = special:konsole, on-created-empty:konsole
bind = SUPER_L_SHIFT_L, t, togglespecialworkspace, konsole # TODO: SUPER_L_SHIFT_L is actually XF86Assistant, but it's not available in hyprland yet
bindo = SUPER, t, togglespecialworkspace, konsole

# spotify
workspace = special:spotify, on-created-empty:spotify
windowrule = workspace special:spotify, class:^(Spotify)$
bind = SUPER_L_SHIFT_L, m, togglespecialworkspace, spotify

# signal
workspace = special:signal, on-created-empty:signal desktop
windowrule = workspace special:signal, title:^(Signal)$
bind = SUPER_L_SHIFT_L, s, togglespecialworkspace, signal

# whatsapp
workspace = special:whatsapp, on-created-empty:wasistlos
windowrule = workspace special:whatsapp, title:^(WasIstLos)$
bind = SUPER_L_SHIFT_L, w, togglespecialworkspace, whatsapp
